/* PARKER BECKETT AUTHORITATIVE SITE CONFIGURATION
   Version 1.3: catalog metadata, streaming links, and video settings live here.

   ADD A STREAMING URL
   1. Find the song slug under songs (for example, "blue-light").
   2. Paste the official HTTPS song URL into only that platform's empty quotes:
      "spotify": "https://open.spotify.com/track/..."
      "appleMusic": "https://music.apple.com/..."
      "amazonMusic": "https://music.amazon.com/..."
      "youtubeMusic": "https://music.youtube.com/..."
      "pandora": "https://www.pandora.com/..."
      "deezer": "https://www.deezer.com/..."
      "tidal": "https://tidal.com/..."
   Leaving a value empty keeps that one button unavailable. Never paste a general
   artist/profile URL when a verified song URL is required.

   ADD AN OFFICIAL VIDEO
   Use only a privacy-enhanced embed URL in this exact form:
   "youtubeEmbedUrl": "https://www.youtube-nocookie.com/embed/VIDEO_ID"
   Do not add autoplay parameters. Put an optional 16:9 thumbnail path in
   "videoThumbnail" (for example, "assets/images/blue-light-video.webp").

   Dates use ISO YYYY-MM-DD internally. Do not invent missing URLs or credits.
*/
window.PARKER_BECKETT_CONFIG = {
  "contactEmail": "corey@217recovery.com",
  "album": {
    "title": "The Forecast",
    "releaseDate": "2026-06-26",
    "releaseDateDisplay": "June 26, 2026",
    "trackCount": 15,
    "trackSlugs": [
      "aware",
      "looks-fine-to-me",
      "dead-end",
      "merrily",
      "no-return",
      "after-all",
      "movies",
      "bubblegum-tuesday",
      "sorry",
      "on-air",
      "what-have-i-done",
      "blue-light",
      "normal",
      "i-was-the-island",
      "seattle"
    ]
  },
  "songs": {
    "aware": {
      "title": "Aware",
      "slug": "aware",
      "isrc": "QT3F52623418",
      "releaseType": "single_later_included_on_album",
      "originalReleaseDate": "2026-06-18",
      "originalReleaseDateDisplay": "June 18, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": true,
      "debutedOnAlbum": false,
      "standaloneSingle": false,
      "artworkPath": "assets/images/forecast.jpeg",
      "songPagePath": "songs/aware.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/forecast.jpeg"
    },
    "looks-fine-to-me": {
      "title": "Looks Fine to Me",
      "slug": "looks-fine-to-me",
      "isrc": "QT3F42662021",
      "releaseType": "single_later_included_on_album",
      "originalReleaseDate": "2026-06-07",
      "originalReleaseDateDisplay": "June 7, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": true,
      "debutedOnAlbum": false,
      "standaloneSingle": false,
      "artworkPath": "assets/images/looks-fine-to-me.jpg",
      "songPagePath": "songs/looks-fine-to-me.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/looks-fine-to-me.jpg"
    },
    "dead-end": {
      "title": "Dead End",
      "slug": "dead-end",
      "isrc": "QT3F72610084",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/dead-end.jpeg",
      "songPagePath": "songs/dead-end.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/dead-end.jpeg"
    },
    "merrily": {
      "title": "Merrily",
      "slug": "merrily",
      "isrc": "QT3F42661902",
      "releaseType": "single_later_included_on_album",
      "originalReleaseDate": "2026-05-31",
      "originalReleaseDateDisplay": "May 31, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": true,
      "debutedOnAlbum": false,
      "standaloneSingle": false,
      "artworkPath": "assets/images/merrily.jpeg",
      "songPagePath": "songs/merrily.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/merrily.jpeg"
    },
    "no-return": {
      "title": "No Return",
      "slug": "no-return",
      "isrc": "QT3F52617991",
      "releaseType": "single_later_included_on_album",
      "originalReleaseDate": "2026-06-11",
      "originalReleaseDateDisplay": "June 11, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": true,
      "debutedOnAlbum": false,
      "standaloneSingle": false,
      "artworkPath": "assets/images/no-return.jpeg",
      "songPagePath": "songs/no-return.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/no-return.jpeg"
    },
    "after-all": {
      "title": "After All",
      "slug": "after-all",
      "isrc": "QT3F72610085",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/after-all.jpeg",
      "songPagePath": "songs/after-all.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/after-all.jpeg"
    },
    "movies": {
      "title": "Movies",
      "slug": "movies",
      "isrc": "QT3F72610086",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/movies.jpg",
      "songPagePath": "songs/movies.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/movies.jpg"
    },
    "bubblegum-tuesday": {
      "title": "Bubblegum Tuesday",
      "slug": "bubblegum-tuesday",
      "isrc": "QT3F72610087",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/forecast.jpeg",
      "songPagePath": "songs/bubblegum-tuesday.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/forecast.jpeg"
    },
    "sorry": {
      "title": "Sorry",
      "slug": "sorry",
      "isrc": "QT3F72610088",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/sorry.jpeg",
      "songPagePath": "songs/sorry.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/sorry.jpeg"
    },
    "on-air": {
      "title": "On Air",
      "slug": "on-air",
      "isrc": "QT3F72610089",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/on-air.jpeg",
      "songPagePath": "songs/on-air.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/on-air.jpeg"
    },
    "what-have-i-done": {
      "title": "What Have I Done",
      "slug": "what-have-i-done",
      "isrc": "QT3F72610090",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/what-have-i-done.jpeg",
      "songPagePath": "songs/what-have-i-done.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/what-have-i-done.jpeg"
    },
    "blue-light": {
      "title": "Blue Light",
      "slug": "blue-light",
      "isrc": "QT3F72610091",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/blue-light.jpg",
      "songPagePath": "songs/blue-light.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/blue-light.jpg"
    },
    "normal": {
      "title": "Normal",
      "slug": "normal",
      "isrc": "QT3F72610092",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/gallery.jpeg",
      "songPagePath": "songs/normal.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/gallery.jpeg"
    },
    "i-was-the-island": {
      "title": "I Was the Island",
      "slug": "i-was-the-island",
      "isrc": "QT3F72610093",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/hero.jpeg",
      "songPagePath": "songs/i-was-the-island.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/hero.jpeg"
    },
    "seattle": {
      "title": "Seattle",
      "slug": "seattle",
      "isrc": "QT3F72610094",
      "releaseType": "album_track",
      "originalReleaseDate": "2026-06-26",
      "originalReleaseDateDisplay": "June 26, 2026",
      "albumName": "The Forecast",
      "albumReleaseDate": "2026-06-26",
      "albumReleaseDateDisplay": "June 26, 2026",
      "preAlbumSingle": false,
      "debutedOnAlbum": true,
      "standaloneSingle": false,
      "artworkPath": "assets/images/seattle.jpeg",
      "songPagePath": "songs/seattle.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/seattle.jpeg"
    },
    "bad-idea-tourettes": {
      "title": "Bad Idea Tourette's",
      "slug": "bad-idea-tourettes",
      "isrc": "QT3FA2635455",
      "releaseType": "standalone_single",
      "originalReleaseDate": "2026-06-07",
      "originalReleaseDateDisplay": "June 7, 2026",
      "albumName": "",
      "albumReleaseDate": "",
      "albumReleaseDateDisplay": "",
      "preAlbumSingle": false,
      "debutedOnAlbum": false,
      "standaloneSingle": true,
      "artworkPath": "assets/images/forecast.jpeg",
      "songPagePath": "songs/bad-idea-tourettes.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/forecast.jpeg"
    },
    "run-it-straight": {
      "title": "Run It Straight",
      "slug": "run-it-straight",
      "isrc": "QT6EF2616658",
      "releaseType": "standalone_single",
      "originalReleaseDate": "2026-06-28",
      "originalReleaseDateDisplay": "June 28, 2026",
      "albumName": "",
      "albumReleaseDate": "",
      "albumReleaseDateDisplay": "",
      "preAlbumSingle": false,
      "debutedOnAlbum": false,
      "standaloneSingle": true,
      "artworkPath": "assets/images/run-it-straight.jpeg",
      "songPagePath": "songs/run-it-straight.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/run-it-straight.jpeg"
    },
    "already-in": {
      "title": "Already In",
      "slug": "already-in",
      "isrc": "QT6F62657669",
      "releaseType": "standalone_single",
      "originalReleaseDate": "2026-07-14",
      "originalReleaseDateDisplay": "July 14, 2026",
      "albumName": "",
      "albumReleaseDate": "",
      "albumReleaseDateDisplay": "",
      "preAlbumSingle": false,
      "debutedOnAlbum": false,
      "standaloneSingle": true,
      "artworkPath": "assets/images/already-in.jpg",
      "songPagePath": "songs/already-in.html",
      "streaming": {
        "spotify": "",
        "appleMusic": "",
        "amazonMusic": "",
        "youtubeMusic": "",
        "pandora": "",
        "deezer": "",
        "tidal": ""
      },
      "youtubeEmbedUrl": "",
      "videoThumbnail": "",
      "lyricsStatus": "complete",
      "storyStatus": "placeholder",
      "commentaryStatus": "needs_confirmation",
      "confirmedCredits": {
        "musicAndLyrics": "Corey Winfield",
        "executiveProducer": "Corey Winfield",
        "label": "Soul Tech Records"
      },
      "lyricSheetPath": "",
      "openGraphImage": "assets/images/already-in.jpg"
    }
  },
  "version": "1.3"
};
